import { FC, ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

interface IRootLayout {
  children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
